name: Run Tests

on:
  push:
    branches:
      - main  # Change this if your main branch has a different name

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Change this to your Python version

    - name: Install dependencies
      run:
        pip install pytest

    - name: Run tests
      run: pytest

    - name: Save test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: test-reports
